//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class task_TaskDetails
    {
        public int id { get; set; }
        [Display(Name = "Task Name")]
        public string taskName { get; set; }
        [Display(Name = "Group 1")]
        public string group1 { get; set; }
        [Display(Name = "Group 2")]
        public string group2 { get; set; }
        [Display(Name = "Group 3")]
        public string group3 { get; set; }
        [Display(Name = "Group 4")]
        public string group4 { get; set; }
        [Display(Name = "Group IsActive")]
        public string isActive { get; set; }
        [Display(Name = "Date")]
        public System.DateTime taskDate { get; set; }
    }
}
